/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    dev: DevAuthOperations;
    usuario: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    dev: Dev;
    archivo: Archivo;
    usuario: Usuario;
    ciudadano: Ciudadano;
    'catalogo-etapa': CatalogoEtapa;
    tipo_tramite: TipoTramite;
    clase_licencia: ClaseLicencia;
    examen: Examan;
    pregunta: Pregunta;
    opcion: Opcion;
    'examen-pregunta': ExamenPregunta;
    'agenda-recurso': AgendaRecurso;
    'proceso-plantilla': ProcesoPlantilla;
    'proceso-paso': ProcesoPaso;
    tramite: Tramite;
    'emision-licencia': EmisionLicencia;
    'tramite-categoria-seleccionada': TramiteCategoriaSeleccionada;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    dev: DevSelect<false> | DevSelect<true>;
    archivo: ArchivoSelect<false> | ArchivoSelect<true>;
    usuario: UsuarioSelect<false> | UsuarioSelect<true>;
    ciudadano: CiudadanoSelect<false> | CiudadanoSelect<true>;
    'catalogo-etapa': CatalogoEtapaSelect<false> | CatalogoEtapaSelect<true>;
    tipo_tramite: TipoTramiteSelect<false> | TipoTramiteSelect<true>;
    clase_licencia: ClaseLicenciaSelect<false> | ClaseLicenciaSelect<true>;
    examen: ExamenSelect<false> | ExamenSelect<true>;
    pregunta: PreguntaSelect<false> | PreguntaSelect<true>;
    opcion: OpcionSelect<false> | OpcionSelect<true>;
    'examen-pregunta': ExamenPreguntaSelect<false> | ExamenPreguntaSelect<true>;
    'agenda-recurso': AgendaRecursoSelect<false> | AgendaRecursoSelect<true>;
    'proceso-plantilla': ProcesoPlantillaSelect<false> | ProcesoPlantillaSelect<true>;
    'proceso-paso': ProcesoPasoSelect<false> | ProcesoPasoSelect<true>;
    tramite: TramiteSelect<false> | TramiteSelect<true>;
    'emision-licencia': EmisionLicenciaSelect<false> | EmisionLicenciaSelect<true>;
    'tramite-categoria-seleccionada': TramiteCategoriaSeleccionadaSelect<false> | TramiteCategoriaSeleccionadaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user:
    | (Dev & {
        collection: 'dev';
      })
    | (Usuario & {
        collection: 'usuario';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface DevAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dev".
 */
export interface Dev {
  id: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archivo".
 */
export interface Archivo {
  id: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuario".
 */
export interface Usuario {
  id: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ciudadano".
 */
export interface Ciudadano {
  id: string;
  dni: string;
  nombre: string;
  apellido: string;
  email: string;
  fecha_nacimiento: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalogo-etapa".
 */
export interface CatalogoEtapa {
  id: string;
  /**
   * Ej: Papeles, Curso, Teorico, Practico, Medico
   */
  nombre: string;
  /**
   * Si es TRUE (Practico), se genera una fila por cada categoria solicitada
   */
  requiere_turno?: boolean | null;
  /**
   * Habilita examen en PC
   */
  es_digital?: boolean | null;
  /**
   * Pide cargar ID Nacional
   */
  es_carga_fut?: boolean | null;
  /**
   * Si es TRUE (Practico), se genera una fila por cada categoria solicitada
   */
  es_multiplicable_por_clase?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipo_tramite".
 */
export interface TipoTramite {
  id: string;
  /**
   * Ej: Original, Renovacion, Ampliacion
   */
  nombre: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clase_licencia".
 */
export interface ClaseLicencia {
  id: string;
  /**
   * Ej: A, B, C, D4
   */
  codigo: string;
  nombre?: string | null;
  descripcion?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "examen".
 */
export interface Examan {
  id: string;
  titulo: string;
  descripcion?: string | null;
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pregunta".
 */
export interface Pregunta {
  id: string;
  enunciado: string;
  archivo?: (string | null) | Archivo;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opcion".
 */
export interface Opcion {
  id: string;
  pregunta?: (string | null) | Pregunta;
  texto_opcion?: string | null;
  imagen_opcion?: (string | null) | Archivo;
  es_correcta?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "examen-pregunta".
 */
export interface ExamenPregunta {
  id: string;
  examen?: (string | null) | Examan;
  pregunta?: (string | null) | Pregunta;
  orden?: number | null;
  puntaje?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agenda-recurso".
 */
export interface AgendaRecurso {
  id: string;
  /**
   * Ej: Pista de Motos, Box Medico
   */
  nombre: string;
  capacidad?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proceso-plantilla".
 */
export interface ProcesoPlantilla {
  id: string;
  /**
   * Ej: Workflow Licencia Original
   */
  nombre: string;
  clase_licencia?: (string | null) | ClaseLicencia;
  tipo_tramite?: (string | null) | TipoTramite;
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proceso-paso".
 */
export interface ProcesoPaso {
  id: string;
  plantilla?: (string | null) | ProcesoPlantilla;
  etapa?: (string | null) | CatalogoEtapa;
  orden?: number | null;
  es_bloqueante?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tramite".
 */
export interface Tramite {
  id: string;
  ciudadano: string | Ciudadano;
  plantilla: string | ProcesoPlantilla;
  codigo_interno: string;
  fut: string;
  estado_global: string;
  fecha_inicio: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emision-licencia".
 */
export interface EmisionLicencia {
  id: string;
  tramite: string | Tramite;
  fecha_emision: string;
  numero_control_plastico: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tramite-categoria-seleccionada".
 */
export interface TramiteCategoriaSeleccionada {
  id: string;
  tramite: string | Tramite;
  clase_licencia: string | ClaseLicencia;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'dev';
        value: string | Dev;
      } | null)
    | ({
        relationTo: 'archivo';
        value: string | Archivo;
      } | null)
    | ({
        relationTo: 'usuario';
        value: string | Usuario;
      } | null)
    | ({
        relationTo: 'ciudadano';
        value: string | Ciudadano;
      } | null)
    | ({
        relationTo: 'catalogo-etapa';
        value: string | CatalogoEtapa;
      } | null)
    | ({
        relationTo: 'tipo_tramite';
        value: string | TipoTramite;
      } | null)
    | ({
        relationTo: 'clase_licencia';
        value: string | ClaseLicencia;
      } | null)
    | ({
        relationTo: 'examen';
        value: string | Examan;
      } | null)
    | ({
        relationTo: 'pregunta';
        value: string | Pregunta;
      } | null)
    | ({
        relationTo: 'opcion';
        value: string | Opcion;
      } | null)
    | ({
        relationTo: 'examen-pregunta';
        value: string | ExamenPregunta;
      } | null)
    | ({
        relationTo: 'agenda-recurso';
        value: string | AgendaRecurso;
      } | null)
    | ({
        relationTo: 'proceso-plantilla';
        value: string | ProcesoPlantilla;
      } | null)
    | ({
        relationTo: 'proceso-paso';
        value: string | ProcesoPaso;
      } | null)
    | ({
        relationTo: 'tramite';
        value: string | Tramite;
      } | null)
    | ({
        relationTo: 'emision-licencia';
        value: string | EmisionLicencia;
      } | null)
    | ({
        relationTo: 'tramite-categoria-seleccionada';
        value: string | TramiteCategoriaSeleccionada;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'dev';
        value: string | Dev;
      }
    | {
        relationTo: 'usuario';
        value: string | Usuario;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'dev';
        value: string | Dev;
      }
    | {
        relationTo: 'usuario';
        value: string | Usuario;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dev_select".
 */
export interface DevSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archivo_select".
 */
export interface ArchivoSelect<T extends boolean = true> {
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuario_select".
 */
export interface UsuarioSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ciudadano_select".
 */
export interface CiudadanoSelect<T extends boolean = true> {
  dni?: T;
  nombre?: T;
  apellido?: T;
  email?: T;
  fecha_nacimiento?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalogo-etapa_select".
 */
export interface CatalogoEtapaSelect<T extends boolean = true> {
  nombre?: T;
  requiere_turno?: T;
  es_digital?: T;
  es_carga_fut?: T;
  es_multiplicable_por_clase?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipo_tramite_select".
 */
export interface TipoTramiteSelect<T extends boolean = true> {
  nombre?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clase_licencia_select".
 */
export interface ClaseLicenciaSelect<T extends boolean = true> {
  codigo?: T;
  nombre?: T;
  descripcion?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "examen_select".
 */
export interface ExamenSelect<T extends boolean = true> {
  titulo?: T;
  descripcion?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pregunta_select".
 */
export interface PreguntaSelect<T extends boolean = true> {
  enunciado?: T;
  archivo?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opcion_select".
 */
export interface OpcionSelect<T extends boolean = true> {
  pregunta?: T;
  texto_opcion?: T;
  imagen_opcion?: T;
  es_correcta?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "examen-pregunta_select".
 */
export interface ExamenPreguntaSelect<T extends boolean = true> {
  examen?: T;
  pregunta?: T;
  orden?: T;
  puntaje?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agenda-recurso_select".
 */
export interface AgendaRecursoSelect<T extends boolean = true> {
  nombre?: T;
  capacidad?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proceso-plantilla_select".
 */
export interface ProcesoPlantillaSelect<T extends boolean = true> {
  nombre?: T;
  clase_licencia?: T;
  tipo_tramite?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proceso-paso_select".
 */
export interface ProcesoPasoSelect<T extends boolean = true> {
  plantilla?: T;
  etapa?: T;
  orden?: T;
  es_bloqueante?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tramite_select".
 */
export interface TramiteSelect<T extends boolean = true> {
  ciudadano?: T;
  plantilla?: T;
  codigo_interno?: T;
  fut?: T;
  estado_global?: T;
  fecha_inicio?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emision-licencia_select".
 */
export interface EmisionLicenciaSelect<T extends boolean = true> {
  tramite?: T;
  fecha_emision?: T;
  numero_control_plastico?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tramite-categoria-seleccionada_select".
 */
export interface TramiteCategoriaSeleccionadaSelect<T extends boolean = true> {
  tramite?: T;
  clase_licencia?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}