/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    dev: DevAuthOperations;
    usuario: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    dev: Dev;
    archivo: Archivo;
    usuario: Usuario;
    ciudadano: Ciudadano;
    tramite: Tramite;
    'tramite-proceso': TramiteProceso;
    'tramite-progreso': TramiteProgreso;
    turno: Turno;
    pregunta: Pregunta;
    opcion: Opcion;
    examen: Examan;
    'examen-pregunta': ExamenPregunta;
    'intento-examen': IntentoExaman;
    'respuesta-seleccionada': RespuestaSeleccionada;
    'emision-licencia': EmisionLicencia;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    tramite: {
      procesos: 'tramite-proceso';
    };
    'tramite-proceso': {
      progresos: 'tramite-progreso';
    };
    'tramite-progreso': {
      turnos: 'turno';
    };
  };
  collectionsSelect: {
    dev: DevSelect<false> | DevSelect<true>;
    archivo: ArchivoSelect<false> | ArchivoSelect<true>;
    usuario: UsuarioSelect<false> | UsuarioSelect<true>;
    ciudadano: CiudadanoSelect<false> | CiudadanoSelect<true>;
    tramite: TramiteSelect<false> | TramiteSelect<true>;
    'tramite-proceso': TramiteProcesoSelect<false> | TramiteProcesoSelect<true>;
    'tramite-progreso': TramiteProgresoSelect<false> | TramiteProgresoSelect<true>;
    turno: TurnoSelect<false> | TurnoSelect<true>;
    pregunta: PreguntaSelect<false> | PreguntaSelect<true>;
    opcion: OpcionSelect<false> | OpcionSelect<true>;
    examen: ExamenSelect<false> | ExamenSelect<true>;
    'examen-pregunta': ExamenPreguntaSelect<false> | ExamenPreguntaSelect<true>;
    'intento-examen': IntentoExamenSelect<false> | IntentoExamenSelect<true>;
    'respuesta-seleccionada': RespuestaSeleccionadaSelect<false> | RespuestaSeleccionadaSelect<true>;
    'emision-licencia': EmisionLicenciaSelect<false> | EmisionLicenciaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Dev | Usuario;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface DevAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Colección de desarrollo para testing y pruebas
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dev".
 */
export interface Dev {
  id: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'dev';
}
/**
 * Gestión de archivos y documentos del sistema (imágenes de preguntas, documentos adjuntos, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archivo".
 */
export interface Archivo {
  id: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Usuarios del sistema con autenticación. Gestiona acceso al panel administrativo
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuario".
 */
export interface Usuario {
  id: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'usuario';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ciudadano".
 */
export interface Ciudadano {
  id: string;
  dni: string;
  nombre: string;
  apellido: string;
  email: string;
  fecha_nacimiento: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tramite".
 */
export interface Tramite {
  id: string;
  ciudadano: string | Ciudadano;
  procesos?: {
    docs?: (string | TramiteProceso)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  fut?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tramite-proceso".
 */
export interface TramiteProceso {
  id: string;
  tramite: string | Tramite;
  proceso: 'Licencia Original A1.1' | 'Licencia Original A1.2';
  progresos?: {
    docs?: (string | TramiteProgreso)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tramite-progreso".
 */
export interface TramiteProgreso {
  id: string;
  tramite_proceso: string | TramiteProceso;
  etapa: number;
  estado: 'EN CURSO' | 'CANCELADO' | 'FINALIZADO' | 'SUSPENDIDO';
  turnos?: {
    docs?: (string | Turno)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  aprobado_por_usuario?: (string | null) | Usuario;
  fecha_aprobacion?: string | null;
  observaciones?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Asignación de turnos. Vincula un paso específico del progreso con un recurso y fecha/hora
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "turno".
 */
export interface Turno {
  id: string;
  tramite: string | TramiteProgreso;
  area: 'Teórico' | 'Práctico' | 'Psicofísico' | 'Curso' | 'Licencias' | 'Otro';
  fecha_hora_inicio: string;
  fecha_hora_fin: string;
  estado: 'RESERVADO' | 'AUSENTE' | 'FINALIZADO' | 'CANCELADO';
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Banco de preguntas para exámenes teóricos. Cada pregunta puede incluir imagen
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pregunta".
 */
export interface Pregunta {
  id: string;
  enunciado: string;
  archivo?: (string | null) | Archivo;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Opciones de respuesta para preguntas. Soporta múltiples respuestas correctas (checkboxes)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opcion".
 */
export interface Opcion {
  id: string;
  pregunta?: (string | null) | Pregunta;
  texto_opcion?: string | null;
  imagen_opcion?: (string | null) | Archivo;
  es_correcta?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Banco de exámenes teóricos para licencias de conducir
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "examen".
 */
export interface Examan {
  id: string;
  titulo: string;
  descripcion?: string | null;
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Relación entre exámenes y preguntas. Define qué preguntas componen cada examen, su orden y puntaje
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "examen-pregunta".
 */
export interface ExamenPregunta {
  id: string;
  examen?: (string | null) | Examan;
  pregunta?: (string | null) | Pregunta;
  orden?: number | null;
  puntaje?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Registro de sesiones de examen de ciudadanos. Almacena fecha inicio/fin, nota final y resultado (aprobado/desaprobado)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intento-examen".
 */
export interface IntentoExaman {
  id: string;
  tramite_progreso: string | TramiteProgreso;
  examen: string | Examan;
  fecha_inicio: string;
  fecha_fin: string;
  nota_final: number;
  aprobado: boolean;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Respuestas marcadas por ciudadanos durante exámenes. Guarda cada opción seleccionada para auditoría detallada
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "respuesta-seleccionada".
 */
export interface RespuestaSeleccionada {
  id: string;
  intento: string | IntentoExaman;
  pregunta: string | Pregunta;
  opcion: string | Opcion;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Registro de emisión final de licencias. Almacena fecha de emisión, usuario emisor y número de control del plástico
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emision-licencia".
 */
export interface EmisionLicencia {
  id: string;
  tramite: string | Tramite;
  fecha_emision: string;
  numero_control_plastico: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'dev';
        value: string | Dev;
      } | null)
    | ({
        relationTo: 'archivo';
        value: string | Archivo;
      } | null)
    | ({
        relationTo: 'usuario';
        value: string | Usuario;
      } | null)
    | ({
        relationTo: 'ciudadano';
        value: string | Ciudadano;
      } | null)
    | ({
        relationTo: 'tramite';
        value: string | Tramite;
      } | null)
    | ({
        relationTo: 'tramite-proceso';
        value: string | TramiteProceso;
      } | null)
    | ({
        relationTo: 'tramite-progreso';
        value: string | TramiteProgreso;
      } | null)
    | ({
        relationTo: 'turno';
        value: string | Turno;
      } | null)
    | ({
        relationTo: 'pregunta';
        value: string | Pregunta;
      } | null)
    | ({
        relationTo: 'opcion';
        value: string | Opcion;
      } | null)
    | ({
        relationTo: 'examen';
        value: string | Examan;
      } | null)
    | ({
        relationTo: 'examen-pregunta';
        value: string | ExamenPregunta;
      } | null)
    | ({
        relationTo: 'intento-examen';
        value: string | IntentoExaman;
      } | null)
    | ({
        relationTo: 'respuesta-seleccionada';
        value: string | RespuestaSeleccionada;
      } | null)
    | ({
        relationTo: 'emision-licencia';
        value: string | EmisionLicencia;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'dev';
        value: string | Dev;
      }
    | {
        relationTo: 'usuario';
        value: string | Usuario;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'dev';
        value: string | Dev;
      }
    | {
        relationTo: 'usuario';
        value: string | Usuario;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dev_select".
 */
export interface DevSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archivo_select".
 */
export interface ArchivoSelect<T extends boolean = true> {
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuario_select".
 */
export interface UsuarioSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ciudadano_select".
 */
export interface CiudadanoSelect<T extends boolean = true> {
  dni?: T;
  nombre?: T;
  apellido?: T;
  email?: T;
  fecha_nacimiento?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tramite_select".
 */
export interface TramiteSelect<T extends boolean = true> {
  ciudadano?: T;
  procesos?: T;
  fut?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tramite-proceso_select".
 */
export interface TramiteProcesoSelect<T extends boolean = true> {
  tramite?: T;
  proceso?: T;
  progresos?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tramite-progreso_select".
 */
export interface TramiteProgresoSelect<T extends boolean = true> {
  tramite_proceso?: T;
  etapa?: T;
  estado?: T;
  turnos?: T;
  aprobado_por_usuario?: T;
  fecha_aprobacion?: T;
  observaciones?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "turno_select".
 */
export interface TurnoSelect<T extends boolean = true> {
  tramite?: T;
  area?: T;
  fecha_hora_inicio?: T;
  fecha_hora_fin?: T;
  estado?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pregunta_select".
 */
export interface PreguntaSelect<T extends boolean = true> {
  enunciado?: T;
  archivo?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opcion_select".
 */
export interface OpcionSelect<T extends boolean = true> {
  pregunta?: T;
  texto_opcion?: T;
  imagen_opcion?: T;
  es_correcta?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "examen_select".
 */
export interface ExamenSelect<T extends boolean = true> {
  titulo?: T;
  descripcion?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "examen-pregunta_select".
 */
export interface ExamenPreguntaSelect<T extends boolean = true> {
  examen?: T;
  pregunta?: T;
  orden?: T;
  puntaje?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intento-examen_select".
 */
export interface IntentoExamenSelect<T extends boolean = true> {
  tramite_progreso?: T;
  examen?: T;
  fecha_inicio?: T;
  fecha_fin?: T;
  nota_final?: T;
  aprobado?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "respuesta-seleccionada_select".
 */
export interface RespuestaSeleccionadaSelect<T extends boolean = true> {
  intento?: T;
  pregunta?: T;
  opcion?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emision-licencia_select".
 */
export interface EmisionLicenciaSelect<T extends boolean = true> {
  tramite?: T;
  fecha_emision?: T;
  numero_control_plastico?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}